# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !
#
{
    'name': 'Modulo de Reparación y Seguimiento',
    'version': '1.0',
    'depends': ['base','unefa_configuracion','unefa_usuarios','unefa_pensum','unefa_planificacion_semestre','unefa_inscripcion','unefa_evaluacion_notas'],
    'author': 'TEG Rodney Ruiz',
    'category': '',
    'description': """
        Incluye:
        Cronograma de las Reparaciones
        Prueba de Reparacion
        Seguimiento de Notas
    """,
    'update_xml': [],
    "data" : [
        'views/unefa_reparacion/menu_views.xml',
        'views/unefa_reparacion/cronograma_rep_view.xml',
        'views/unefa_reparacion/prueba_rep_view.xml',
        'views/unefa_seguimiento/menu_views.xml',
        'views/unefa_seguimiento/seguimiento_view.xml',
        'security/group_administrador/ir.model.access.csv',
        'security/group_coordinador/ir.model.access.csv',
        'security/group_estudiantes/ir.model.access.csv',
        'security/group_profesores/ir.model.access.csv',
        ],
    'installable': True,
    'auto_install': False,
}
