# -*- coding: utf-8 -*-
##############################################################################
#
#    Programa realizado por, Jeison Pernía y Jonathan Reyes en el marco
#    del plan de estudios de la UNEFA, como TRABAJO ESPECIAL DE GRADO,
#    con el fin de optar al título de Ingeniero de Sistemas.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !
#
{
    'name': 'Planificación de Semestre',
    'version': '1.0',
    'depends': ['base','unefa_configuracion','unefa_pensum','unefa_usuarios'],
    'authors': 'Jeison Pernía y Jonathan Reyes',
    'category': 'Configuración Técnica',
    'description': """
    Este módulo configura la planificación de semetsre emanada de las 
    autoridades de la UNEFA a las coordinaciones.
    """,
    'update_xml': [],
    "data" : [
        'views/configuracion/unefa_configuracion.xml',
        'views/planificacion_semestre/unefa_planificacion_semestre_view.xml',
        'data/activ_inscripcion_sem_data.xml',
        'data/cronogr_actividades_data.xml',
        'security/group_unefa_admin/ir.model.access.csv',
        'security/group_unefa_coor/ir.model.access.csv',
        'security/group_unefa_est/ir.model.access.csv',
        'security/group_unefa_eval/ir.model.access.csv',
        'security/group_unefa_prof/ir.model.access.csv',
        'security/group_unefa_secret/ir.model.access.csv',
        ],
    'installable': True,
    'auto_install': False,
}

