# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !
#
{
    'name': 'Plan de Evaluación y Carga de Notas',
    'version': '1.0',
    'depends': ['base_setup','unefa_configuracion','unefa_usuarios','unefa_pensum','unefa_planificacion_semestre','unefa_inscripcion'],
    'author': 'UNEFA_Ernesto_Amanda',
    'category': '',
    'description': """
    Modulos ACDA, PDE, CDN , PDAA
    """,
    'update_xml': [],
    "data" : [

        "views/pde/plan_evaluacion_view.xml",
        "views/pde/unefa_corte_pde_view.xml",
        "views/pde/unefa_evaluacion_pde_view.xml",
        "views/pde/unefa_tipo_contenido_pde_view.xml",
        "views/pde/unefa_tipo_evaluacion_view.xml",
	 
        "views/pdaa/plan_actividades_academicas_view.xml",
    
        "views/cdn/unefa_carga_notas_view.xml",
        "views/cdn/unefa_cdn_view.xml",
        "views/cdn/unefa_evaluacion_continua_view.xml",
    
    
        "views/acda/unefa_acta_contrato_aprendizaje_view.xml",
    
        "data/cortes_data.xml",
        "data/estudiantes_data.xml",
        
        'security/group_unefa_admin/ir.model.access.csv',
        'security/group_unefa_coor/ir.model.access.csv',
        'security/group_unefa_est/ir.model.access.csv',
        'security/group_unefa_eval/ir.model.access.csv',
        'security/group_unefa_prof/ir.model.access.csv',
        'security/group_unefa_secret/ir.model.access.csv',
    #~ 
	#~ 
	#~ "models/acda/report/unefa_acda_report.xml",
	#~ "views/acda/unefa_acda_template.xml",
	
        ],
    'installable': True,
    'auto_install': False, 
}

